-- LeveLab data is accessed only by the backend (direct Postgres role, bypasses RLS).
-- Enable RLS with no policies so the Supabase public API (anon/authenticated) cannot read or write these tables.
ALTER TABLE "Member" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WellnessProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Consent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Program" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProgramVersion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProgramEnrollment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DailyCheckin" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Product" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Price" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Order" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OrderItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Subscription" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuditEvent" ENABLE ROW LEVEL SECURITY;
